### OVERALL LOOK AT THE DATASET AND SILVER LAYER

In [1]:
import pandas as pd
import numpy as np
import re
from jproperties import Properties
from sqlalchemy import create_engine, text
from sqlalchemy import Numeric
import subprocess
import app.connect_mongodb as cm


# pandas settings
pd.set_option('max.colwidth', 200)
pd.set_option('display.max_rows', 50)

In [2]:
# loading variables from file (db access)

with open("app/app.properties", "r+b") as f:
    p = Properties()
    p.load(f, "utf-8")

### MongoDB Acess (Data Source)

In [3]:
connector  = cm.Connect_MongoDB()
db = connector.connect()
bronze_layer = db.get_collection('bronze')

In [4]:
print(f'Number of data records in the database: {bronze_layer.count_documents({})}')

Number of data records in the database: 2453

### Creating a DataFrame

In [5]:

df = pd.DataFrame(list(bronze_layer.find({})))

df = df.drop_duplicates('data-id')

print(f'Number of data records after deletion of duplicated entries: {df.shape[0]}')
assert df[df['data-id'].duplicated()]['data-id'].sum() == 0, 'We have duplicated ids (data-id) in the DB'

Number of data records after deletion of duplicated entries: 2428

In [6]:
df.head(2)

,_id,link,data-id,atts,date
0,689b36c8f818af343fb1093b,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp,2746686250,"{'ad_type': 'Aluguel', 'sell_price': None, 'rent_price': 'R$ 50.000/mês', 'condo_price': 'não informado', 'address': 'Avenida das Cerejeiras - Jardim Japão, São Paulo - SP', 'rstate_type': 'Terren...",2025-08-12 09:42:48
1,689b36ddf818af343fb1093d,https://www.zapimoveis.com.br/imovel/aluguel-casa-1-quarto-itaim-bibi-sao-paulo-45m2-id-2812103252/?source=ranking%2Crp,2812103252,"{'ad_type': 'Aluguel', 'sell_price': None, 'rent_price': 'R$ 4.500/mês', 'condo_price': 'R$ 1.192', 'address': 'Rua Professor Tamandaré Toledo - Itaim Bibi, São Paulo - SP', 'rstate_type': 'Casas ...",2025-08-12 09:43:09

### Getting Only The Attributes

In [7]:
df_atts =  pd.concat(
        [df[['data-id','link']], pd.json_normalize(df['atts'])],
        axis = 1
)

df_atts.head(2)

,data-id,link,ad_type,sell_price,rent_price,condo_price,address,rstate_type,floorSize,numberOfRooms,...,CORNER_PROPERTY,BEAUTY_ROOM,COVERAGE,LAMINATED_FLOOR,GEMINADA,PATROL,ECO_GARBAGE_COLLECTOR,ORCHID_PLACE,AQUARIUM,FRUIT_TREES
0,2746686250,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp,Aluguel,None,R$ 50.000/mês,não informado,"Avenida das Cerejeiras - Jardim Japão, São Paulo - SP","Terrenos, Lotes e Condomínios para Alugar/",2500 m²,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2812103252,https://www.zapimoveis.com.br/imovel/aluguel-casa-1-quarto-itaim-bibi-sao-paulo-45m2-id-2812103252/?source=ranking%2Crp,Aluguel,None,R$ 4.500/mês,R$ 1.192,"Rua Professor Tamandaré Toledo - Itaim Bibi, São Paulo - SP",Casas Comerciais para Alugar/,45 m²,1 quarto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
## removing comercial as we are not interested for this analysis;

df_atts = df_atts[~df_atts.rstate_type.apply(lambda x: True if re.search('Comerciais', str(x)) else False)]
print(df_atts.rstate_type.unique())

['Terrenos, Lotes e Condomínios para Alugar/' 'Casas à Venda/'
 'Apartamentos para Alugar/' 'Apartamentos à Venda/' 'Sobrados à Venda/'
 'Coberturas à Venda/' 'Sobrados para Alugar/'
 'Casas de Condomínio à Venda/' 'Casas para Alugar/' 'Flats à Venda/'
 'Casas de Condomínio para Alugar/' 'Coberturas para Alugar/'
 'Flats para Alugar/' 'Imóveis para Alugar/' 'Imóveis à Venda/'
 'Kitnets para Alugar/' 'Studios à Venda/' nan]

### Selecting Columns Of Interest

In [9]:
# for _ in df_atts.columns:
#      print(_)

cols_of_interest = [
    'data-id',
    'ad_type', 'rstate_type',
    'rent_price', 'condo_price', 'sell_price',
    'address', 'floorSize', 'numberOfBathroomsTotal',
    'numberOfParkingSpaces',
    'numberOfRooms',
    'numberOfSuites',
    'FURNISHED',
    'AIR_CONDITIONING',
    'HOME_OFFICE',
    'POOL',
    'GYM',
    'SAUNA',
    'LAUNDRY',
    'COWORKING',
    'link'
    ]

# keep only the cols that exist in the dataset; 

cols_of_interest = [x for x in cols_of_interest if x in df_atts.columns]

# change the df
df_atts = df_atts[cols_of_interest]

### % of NaN Values

In [10]:
missing = df_atts.isna().sum()
missing = missing/df_atts.shape[0] * 100
missing.sort_values(ascending=False)

## comments; 
# the null values on the ameneties represents the absence of such elements like GYM or LAUNDRY.
# for others that are mandatory (like having at least sell or rent price and the floor size), its more likely to be an  error that occurred when web scraping.

COWORKING                 99.671997
HOME_OFFICE               98.113981
GYM                       83.804838
LAUNDRY                   82.246822
SAUNA                     73.718737
AIR_CONDITIONING          65.395654
sell_price                62.443624
POOL                      52.111521
FURNISHED                 40.877409
numberOfSuites            27.101271
numberOfParkingSpaces      6.273063
numberOfRooms              1.107011
rent_price                 1.066011
numberOfBathroomsTotal     1.066011
rstate_type                1.025010
ad_type                    1.025010
data-id                    1.025010
condo_price                1.025010
floorSize                  1.025010
address                    1.025010
link                       1.025010
dtype: float64

In [ ]:
df_atts[df_atts.numberOfRooms.isna()]

,data-id,ad_type,rstate_type,rent_price,condo_price,sell_price,address,floorSize,numberOfBathroomsTotal,numberOfParkingSpaces,...,numberOfSuites,FURNISHED,AIR_CONDITIONING,HOME_OFFICE,POOL,GYM,SAUNA,LAUNDRY,COWORKING,link
0,2746686250,Aluguel,"Terrenos, Lotes e Condomínios para Alugar/",R$ 50.000/mês,não informado,None,"Avenida das Cerejeiras - Jardim Japão, São Paulo - SP",2500 m²,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp
2387,2827475749,Aluguel,Kitnets para Alugar/,R$ 2.600/mês,R$ 1,None,"Rua Mário Ribeiro, 1096 - Pitangueiras, Guarujá - SP",40 m²,1 banheiro,1 vaga,...,NaN,Mobiliado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-mobiliado-pitangueiras-guaruja-104m2-id-2827475749/?source=ranking%2Crp
2428,2736666634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-4-quartos-mobiliado-enseada-guaruja-103m2-id-2736666634/?source=ranking%2Crp
2429,2804488052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-mobiliado-pitangueiras-guaruja-103m2-id-2804488052/?source=ranking%2Crp
2430,2663127993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-com-piscina-pitangueiras-guaruja-103m2-id-2663127993/?source=ranking%2Crp
2431,2815604370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-com-piscina-pitangueiras-guaruja-102m2-id-2815604370/?source=ranking%2Crp
2432,2815865619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-pitangueiras-guaruja-102m2-id-2815865619/?source=ranking%2Crp
2433,2809275153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-2-quartos-mobiliado-pitangueiras-guaruja-102m2-id-2809275153/?source=ranking%2Crp
2434,2813868675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-mobiliado-pitangueiras-guaruja-102m2-id-2813868675/?source=ranking%2Crp
2435,2808563161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-2-quartos-com-piscina-pitangueiras-guaruja-102m2-id-2808563161/?source=ranking%2Crp
2436,2788979813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-mobiliado-enseada-guaruja-102m2-id-2788979813/?source=ranking%2Crp
2437,2800748755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-mobiliado-jardim-asturias-guaruja-102m2-id-2800748755/?source=ranking%2Crp
2438,2801518824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-mobiliado-pitangueiras-guaruja-102m2-id-2801518824/?source=ranking%2Crp
2439,2772714027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-3-quartos-jardim-enseada-guaruja-101m2-id-2772714027/?source=ranking%2Crp
2440,2719277593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-mobiliado-pitangueiras-guaruja-101m2-id-2719277593/?source=ranking%2Crp
2441,2726410046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-jardim-enseada-guaruja-101m2-id-2726410046/?source=ranking%2Crp
2442,2816792439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-mobiliado-pitangueiras-guaruja-31m2-id-2816792439/?source=ranking%2Crp
2443,2824780573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-quitinete-1-quarto-enseada-guaruja-30m2-id-2824780573/?source=ranking%2Crp
2444,2825147416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-flat-1-quarto-mobiliado-pitangueiras-guaruja-30m2-id-2825147416/?source=ranking%2Crp
2445,2814836462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-com-churrasqueira-pitangueiras-guaruja-30m2-id-2814836462/?source=ranking%2Crp
2446,2824976287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-mobiliado-jardim-santense-vicente-de-carvalho-guaruja-30m2-id-2824976287/?source=ranking%2Crp
2447,2825521647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-flat-1-quarto-mobiliado-pitangueiras-guaruja-29m2-id-2825521647/?source=ranking%2Crp
2448,2817065221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-quitinete-1-quarto-mobiliado-pitangueiras-guaruja-27m2-id-2817065221/?source=ranking%2Crp
2449,2826209717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-com-piscina-enseada-guaruja-27m2-id-2826209717/?source=ranking%2Crp
2450,2737807487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-enseada-guaruja-27m2-id-2737807487/?source=ranking%2Crp
2451,2825169636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-quitinete-1-quarto-com-ar-condicionado-enseada-guaruja-27m2-id-2825169636/?source=ranking%2Crp
2452,2815980719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-1-quarto-mobiliado-pitangueiras-guaruja-23m2-id-2815980719/?source=ranking%2Crp

### Removing Null Values
<li> if m2 = 0/NA or both rent and sell price are 0/NA, we'll remove the instance

In [12]:
df_atts.shape

(2439, 21)

In [13]:
df_atts = df_atts[~df_atts.floorSize.isnull()]

df_atts = df_atts[
    ~(df_atts.rent_price.isnull()) |
    ~(df_atts.sell_price.isnull())
    ]

In [14]:
df_atts.shape

(2414, 21)

### Data Transformation

<li> Dtypes

In [15]:
# FLOAT 

def func(x):
    pat = re.compile('[\d\.\,\- ]+')

    match = pat.search(str(x))

    if match:
        return match.group(0).replace('.', '')
    else:
        return x



cols_float = ['sell_price', 'rent_price', 'condo_price']

df_atts = df_atts.replace({'isento': np.nan,'não informado': np.nan})

df_atts[cols_float] = df_atts[cols_float].map(func).replace('.', '')

df_atts[cols_float] = df_atts[cols_float].astype(float)

<li> Boolean

In [16]:

cols_bool = ['AIR_CONDITIONING', 'FURNISHED','HOME_OFFICE', 'POOL','GYM', 'LAUNDRY', 'SAUNA', 'COWORKING'] # desired;

cols_bool = [col for col in cols_bool if col in df_atts.columns] # ajusted in relation to the dataset;



df_atts.loc[:, cols_bool] = df_atts[cols_bool].fillna(0) # 0 represents the unpresence of such property; 
df_atts.loc[:, cols_bool]= df_atts[cols_bool].replace(to_replace= ('^(?!0).*'), value = 1, regex= True) # all the rest can be replaced by 1 (True)

/tmp/ipykernel_787588/2694258841.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_atts.loc[:, cols_bool]= df_atts[cols_bool].replace(to_replace= ('^(?!0).*'), value = 1, regex= True) # all the rest can be replaced by 1 (True)

<li> Integer

In [17]:

cols_int = ['floorSize', 'numberOfBathroomsTotal', 'numberOfParkingSpaces', 'numberOfRooms'] + cols_bool
df_atts[cols_int] = df_atts[cols_int].map(func)
df_atts[cols_int] = df_atts[cols_int].fillna(0).astype(int)

### Feature Engineering

In [18]:
def regex_neighbor(x):

    match=re.search('(?<=- )[\w ]+', str(x))
    if match:
        return match.group()
    else:
        return x

df_atts.loc[:, 'neighborhood'] = df_atts.address.apply(regex_neighbor)
df_atts.loc[:, 'numberOfSuites'] = df_atts.numberOfSuites.fillna(0).apply(lambda x: re.search('\d+', str(x)).group())
df_atts['total_rental_price'] = df_atts.condo_price + df_atts.rent_price

# to int;
df_atts['numberOfSuites'] = df_atts.numberOfSuites.astype(int)

In [19]:
for index, cols in df_atts.iterrows():
    
    if not isinstance(cols.address, float):
        address = cols.address.split(',')
        
        n = len(address)

        df_atts.loc[index, 'neighborhood']  = regex_neighbor(address[-2])
        df_atts.loc[index, 'city'] = address[-1].split(' - ')[0].strip()

        if n == 3: # means we have street name;

            df_atts.loc[index, 'street'] = address[-3]
            df_atts.loc[index, 'number'] = address[-2].split('-')[0].strip()

In [20]:
df_atts = df_atts.drop(columns = ['address']) # we can drop;

In [21]:
df_atts.dtypes

data-id                    object
ad_type                    object
rstate_type                object
rent_price                float64
condo_price               float64
sell_price                float64
floorSize                   int64
numberOfBathroomsTotal      int64
numberOfParkingSpaces       int64
numberOfRooms               int64
numberOfSuites              int64
FURNISHED                   int64
AIR_CONDITIONING            int64
HOME_OFFICE                 int64
POOL                        int64
GYM                         int64
SAUNA                       int64
LAUNDRY                     int64
COWORKING                   int64
link                       object
neighborhood               object
total_rental_price        float64
city                       object
street                     object
number                     object
dtype: object

### Data Cleaning

In [22]:
df_atts.loc[:, 'rstate_type'] = df_atts.rstate_type.str[:-1]  # removing '/' at final of each string;

In [23]:


cols_reord = [
             'data-id', 'rstate_type', 'ad_type',
             'rent_price',  'sell_price',  'condo_price', 'total_rental_price', 'floorSize',
             'neighborhood', 'street', 'number', 'city'] + cols_bool + \
            ['numberOfRooms', 'numberOfSuites', 'numberOfBathroomsTotal', 'numberOfParkingSpaces', 'link']

df_atts = df_atts[cols_reord]

In [24]:
renamed_cols = {'data-id': 'id', 
                'rstate_type': 'kind', 'ad_type': 'rent_or_selling', 
                'rent_price':'price_rent', 'sell_price': 'price_sale', 'condo_price': 'price_condominium', 'total_rental_price': 'rent_plus_condo', 
                'floorSize': 'floor_size', 'number': 'address_number',  
                'AIR_CONDITIONING': 'air_conditioning', 'FURNISHED': 'furnished', 'HOME_OFFICE': 'home_office', 
                "POOL": 'pool', "GYM": 'gym', "LAUNDRY": 'laundry', 'SAUNA': 'sauna',
                'numberOfRooms': 'rooms', 'numberOfSuites': 'suites', 'numberOfBathroomsTotal': 'bathrooms', 'numberOfParkingSpaces': 'parking'}


df_atts = df_atts.rename(columns = renamed_cols)

In [25]:
df_atts.head(2)

,id,kind,rent_or_selling,price_rent,price_sale,price_condominium,rent_plus_condo,floor_size,neighborhood,street,...,pool,gym,laundry,sauna,COWORKING,rooms,suites,bathrooms,parking,link
0,2746686250,"Terrenos, Lotes e Condomínios para Alugar",Aluguel,50000.0,NaN,NaN,NaN,2500,Jardim Japão,NaN,...,0,0,0,0,0,0,0,0,0,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp
3,2812097995,Casas à Venda,Venda,8000.0,1722000.0,NaN,NaN,300,Campo Belo,NaN,...,0,0,0,0,0,3,1,3,8,https://www.zapimoveis.com.br/imovel/venda-casa-3-quartos-brooklin-paulista-sao-paulo-300m2-id-2812097995/?source=ranking%2Crp

### Validating Duplicated Listing

In [26]:
# Needed because the same house can be listed by different real estate agencies

columns = list(df_atts.columns)
for i in ['id', 'link']:
    columns.remove(i)

print(f'Number of duplicated listing based on REstate properties: {df_atts.duplicated(subset= columns).sum()}')

Number of duplicated listing based on REstate properties: 25

In [27]:
df_atts = df_atts.drop_duplicates(subset=columns)

df_atts.shape

(2389, 25)

### Estatistical Cleaning

<li> outliers

In [28]:
df_atts_sell = df_atts[~df_atts.price_sale.isna()]
df_atts_rent = df_atts[~df_atts.price_rent.isna()]  # as some adtype listed as "For Sale" may contain the price and be able to rent, we can use .isna()

In [29]:
def plot_box_plot(df, sell_or_rent):

    if sell_or_rent == 'rent':
        box_data = df.price_rent / df.floor_size

    elif sell_or_rent == 'sell':
        box_data = df.price_sale / df.floor_size
    
    else:
        raise NameError

    Q1 = np.percentile(box_data, 25)
    Q3 = np.percentile(box_data, 75)
    IQR = Q3 - Q1

    u_bound = Q3 + 1.5*IQR
    l_bound = Q1 - 1.5*IQR

    return {'u_bound': u_bound, 'l_bound': l_bound}

In [30]:
# IQR to remove outliers based on price/floor_size

rent_bounds = plot_box_plot(df_atts_rent, 'rent')
df_atts_rent_adjusted = df_atts_rent[
    ((df_atts_rent.price_rent / df_atts_rent.floor_size) < rent_bounds.get('u_bound')) &
   ( (df_atts_rent.price_rent / df_atts_rent.floor_size) > rent_bounds.get('l_bound') )
]

sale_bounds = plot_box_plot(df_atts_sell, 'sell')
df_atts_sale_adjusted = df_atts_sell[
    ((df_atts_sell.price_rent / df_atts_sell.floor_size) < sale_bounds.get('u_bound')) &
   ( (df_atts_sell.price_rent / df_atts_sell.floor_size) > sale_bounds.get('l_bound') )
]

In [31]:
# making a new index to slice the original dataframe;
new_index = np.concatenate((df_atts_rent_adjusted.index,df_atts_sale_adjusted.index))
new_index = list(set(new_index))

df_atts = df_atts.loc[new_index, :]

### Postgres Ingestion;

In [32]:
# db credentials come from the file app.properties

uri = p.get('uri').data
engine = create_engine(uri)

with engine.connect() as con:
    con.execute(text("CREATE SCHEMA if not exists zap"))
    con.commit()

In [33]:
# drop views to update silver table; 
with engine.connect() as conn:
    views_list = conn.execute(
    text("""select table_name 
            from information_schema.views
            where table_schema = 'zap' """)).fetchall() # getting the view's name that exists;


    for view in views_list:  # dropping them because it's needed;
        conn.execute(text(f"DROP VIEW zap.{view[0]}"))
        conn.commit() 


df_atts.to_sql('silver_zapimoveis', schema='zap', # now its gonna work;
    con = uri, if_exists='replace', index = False, 
    dtype={'price_rent': Numeric, 'price_sale': Numeric, 'price_condominium': Numeric, 'rent_plus_condo': Numeric})

322

In [34]:
### call run dbt;
subprocess.run("dbt run", shell=True)

19:45:22  Running with dbt=1.9.2
19:45:22  Registered adapter: postgres=1.9.0
19:45:23  Found 1 model, 6 data tests, 1 source, 433 macros
19:45:23
19:45:23  Concurrency: 2 threads (target='dev')
19:45:23
19:45:24  1 of 1 START sql table model zap.gold_floorsize_ranked_avg_prices .............. [RUN]
19:45:24  1 of 1 OK created sql table model zap.gold_floorsize_ranked_avg_prices ......... [SELECT 2322 in 0.36s]
19:45:24
19:45:24  Finished running 1 table model in 0 hours 0 minutes and 0.66 seconds (0.66s).
19:45:24
19:45:24  Completed successfully
19:45:24
19:45:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

CompletedProcess(args='dbt run', returncode=0)

### END

In [35]:
with engine.connect() as conn:
    query = text("SELECT * FROM zap.gold_floorsize_ranked_avg_prices")
    data = conn.execute(query).fetchall()

    df_gold = pd.DataFrame(data)

In [36]:
df_gold.head(3)

,id,kind,rent_or_selling,price_rent,price_sale,price_condominium,rent_plus_condo,floor_size,neighborhood,street,...,laundry,sauna,COWORKING,rooms,suites,bathrooms,parking,link,floor_size_rank,price_rent_per_m2
0,2828692455,Apartamentos à Venda,Venda,230.0,348000.0,None,None,88,Vila Júlia,None,...,1,0,0,3,1,2,1,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-4-quartos-mobiliado-pitangueiras-guaruja-160m2-id-2828692455/?source=ranking%2Crp,C,2.6136363636363636
1,2823932630,Apartamentos à Venda,Venda,190.0,248000.0,750.0,940.0,58,Enseada,None,...,0,0,0,2,0,2,1,https://www.zapimoveis.com.br/imovel/venda-apartamento-3-quartos-mobiliado-pitangueiras-guaruja-114m2-id-2823932630/?source=ranking%2Crp,D,3.2758620689655172
2,2821671915,Apartamentos à Venda,Venda,265.0,448000.0,None,None,71,Balneário Cidade Atlântica,None,...,1,1,0,3,1,3,1,https://www.zapimoveis.com.br/imovel/aluguel-apartamento-4-quartos-mobiliado-enseada-guaruja-130m2-id-2821671915/?source=ranking%2Crp,C,3.7323943661971831

In [37]:
# export and save for using in Tableau (Data Viz)
df_gold.to_csv('zap-gold_data-to_tableau.csv', index = False)