### OVERALL LOOK AT THE DATASET AND SILVER LAYER

In [1]:
import pandas as pd
import numpy as np
import re
from jproperties import Properties
from sqlalchemy import create_engine, text
from sqlalchemy import Numeric
import subprocess
import app.connect_mongodb as cm


# pandas settings
pd.set_option('max.colwidth', 200)
pd.set_option('display.max_rows', 50)

In [2]:
# loading variables from file (db access)

with open("app/app.properties", "r+b") as f:
    p = Properties()
    p.load(f, "utf-8")

### MongoDB Acess (Data Source)

In [3]:
connector  = cm.Connect_MongoDB()
db = connector.connect()
bronze_layer = db.get_collection('bronze')

In [4]:
print(f'Number of data records in the database: {bronze_layer.count_documents({})}')

Number of data records in the database: 122

### Creating a DataFrame

In [5]:

df = pd.DataFrame(list(bronze_layer.find({})))

df = df.drop_duplicates('data-id')

print(f'Number of data records after deletion of duplicated entries: {df.shape[0]}')
assert df[df['data-id'].duplicated()]['data-id'].sum() == 0, 'We have duplicated ids (data-id) in the DB'

Number of data records after deletion of duplicated entries: 122

In [6]:
df.head(2)

,_id,link,data-id,atts,date
0,68995c27679309abf7a0dd72,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp,2746686250,"{'ad_type': 'Aluguel', 'sell_price': None, 'rent_price': 'R$ 50.000/mês', 'condo_price': 'não informado', 'address': 'Avenida das Cerejeiras - Jardim Japão, São Paulo - SP', 'rstate_type': 'Terren...",2025-08-10 23:57:43
1,68995c2f679309abf7a0dd74,https://www.zapimoveis.com.br/imovel/aluguel-casa-1-quarto-itaim-bibi-sao-paulo-45m2-id-2812103252/?source=ranking%2Crp,2812103252,"{'ad_type': 'Aluguel', 'sell_price': None, 'rent_price': 'R$ 4.500/mês', 'condo_price': 'R$ 1.192', 'address': 'Rua Professor Tamandaré Toledo - Itaim Bibi, São Paulo - SP', 'rstate_type': 'Casas ...",2025-08-10 23:57:51

### Getting Only The Attributes

In [7]:
df_atts =  pd.concat(
        [df[['data-id','link']], pd.json_normalize(df['atts'])],
        axis = 1
)

df_atts.head(2)

,data-id,link,ad_type,sell_price,rent_price,condo_price,address,rstate_type,floorSize,numberOfRooms,...,BATHTUB,STAIR,LARGE_KITCHEN,SMART_APARTMENT,PAVED_STREET,LUNCH_ROOM,BAR,BARBECUE_BALCONY,GREEN_SPACE,MASSAGE_ROOM
0,2746686250,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp,Aluguel,None,R$ 50.000/mês,não informado,"Avenida das Cerejeiras - Jardim Japão, São Paulo - SP","Terrenos, Lotes e Condomínios para Alugar/",2500 m²,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2812103252,https://www.zapimoveis.com.br/imovel/aluguel-casa-1-quarto-itaim-bibi-sao-paulo-45m2-id-2812103252/?source=ranking%2Crp,Aluguel,None,R$ 4.500/mês,R$ 1.192,"Rua Professor Tamandaré Toledo - Itaim Bibi, São Paulo - SP",Casas Comerciais para Alugar/,45 m²,1 quarto,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
## removing comercial as we are not interested for this analysis;

df_atts = df_atts[~df_atts.rstate_type.apply(lambda x: True if re.search('Comerciais', str(x)) else False)]
print(df_atts.rstate_type.unique())

['Terrenos, Lotes e Condomínios para Alugar/' 'Casas à Venda/'
 'Apartamentos à Venda/' 'Sobrados à Venda/'
 'Casas de Condomínio à Venda/' 'Sobrados para Alugar/'
 'Apartamentos para Alugar/' 'Coberturas à Venda/' 'Casas para Alugar/'
 'Flats à Venda/' 'Imóveis para Alugar/' 'Coberturas para Alugar/']

### Selecting Columns Of Interest

In [9]:
# for _ in df_atts.columns:
#      print(_)

cols_of_interest = [
    'data-id',
    'ad_type', 'rstate_type',
    'rent_price', 'condo_price', 'sell_price',
    'address', 'floorSize', 'numberOfBathroomsTotal',
    'numberOfParkingSpaces',
    'numberOfRooms',
    'numberOfSuites',
    'FURNISHED',
    'AIR_CONDITIONING',
    'HOME_OFFICE',
    'POOL',
    'GYM',
    'SAUNA',
    'LAUNDRY',
    'COWORKING',
    'link'
    ]

# keep only the cols that exist in the dataset; 

cols_of_interest = [x for x in cols_of_interest if x in df_atts.columns]

# change the df
df_atts = df_atts[cols_of_interest]

### % of NaN Values

In [10]:
missing = df_atts.isna().sum()
missing = missing/df_atts.shape[0] * 100
missing.sort_values(ascending=False)

## comments; 
# the null values on the ameneties represents the absence of such elements like GYM or LAUNDRY.
# for others that are mandatory (like having at least sell or rent price and the floor size), its more likely to be an  error that occurred when web scraping.

SAUNA                     90.654206
HOME_OFFICE               89.719626
FURNISHED                 86.915888
GYM                       85.981308
LAUNDRY                   84.112150
POOL                      81.308411
AIR_CONDITIONING          77.570093
sell_price                49.532710
numberOfSuites            27.102804
numberOfParkingSpaces      1.869159
numberOfBathroomsTotal     0.934579
rent_price                 0.934579
numberOfRooms              0.934579
rstate_type                0.000000
data-id                    0.000000
ad_type                    0.000000
address                    0.000000
condo_price                0.000000
floorSize                  0.000000
link                       0.000000
dtype: float64

In [11]:
df_atts[df_atts.numberOfRooms.isna()]

,data-id,ad_type,rstate_type,rent_price,condo_price,sell_price,address,floorSize,numberOfBathroomsTotal,numberOfParkingSpaces,numberOfRooms,numberOfSuites,FURNISHED,AIR_CONDITIONING,HOME_OFFICE,POOL,GYM,SAUNA,LAUNDRY,link
0,2746686250,Aluguel,"Terrenos, Lotes e Condomínios para Alugar/",R$ 50.000/mês,não informado,None,"Avenida das Cerejeiras - Jardim Japão, São Paulo - SP",2500 m²,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp

### Removing Null Values
<li> if m2 = 0/NA or both rent and sell price are 0/NA, we'll remove the instance

In [12]:
df_atts.shape

(107, 20)

In [13]:
df_atts = df_atts[~df_atts.floorSize.isnull()]

df_atts = df_atts[
    ~(df_atts.rent_price.isnull()) |
    ~(df_atts.sell_price.isnull())
    ]

In [14]:
df_atts.shape

(107, 20)

### Data Transformation

<li> Dtypes

In [15]:
# FLOAT 

def func(x):
    pat = re.compile('[\d\.\,\- ]+')

    match = pat.search(str(x))

    if match:
        return match.group(0).replace('.', '')
    else:
        return x



cols_float = ['sell_price', 'rent_price', 'condo_price']

df_atts = df_atts.replace({'isento': np.nan,'não informado': np.nan})

df_atts[cols_float] = df_atts[cols_float].map(func).replace('.', '')

df_atts[cols_float] = df_atts[cols_float].astype(float)

<li> Boolean

In [16]:

cols_bool = ['AIR_CONDITIONING', 'FURNISHED','HOME_OFFICE', 'POOL','GYM', 'LAUNDRY', 'SAUNA', 'COWORKING'] # desired;

cols_bool = [col for col in cols_bool if col in df_atts.columns] # ajusted in relation to the dataset;



df_atts.loc[:, cols_bool] = df_atts[cols_bool].fillna(0) # 0 represents the unpresence of such property; 
df_atts.loc[:, cols_bool]= df_atts[cols_bool].replace(to_replace= ('^(?!0).*'), value = 1, regex= True) # all the rest can be replaced by 1 (True)

/tmp/ipykernel_86054/2694258841.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_atts.loc[:, cols_bool]= df_atts[cols_bool].replace(to_replace= ('^(?!0).*'), value = 1, regex= True) # all the rest can be replaced by 1 (True)

<li> Integer

In [17]:

cols_int = ['floorSize', 'numberOfBathroomsTotal', 'numberOfParkingSpaces', 'numberOfRooms'] + cols_bool
df_atts[cols_int] = df_atts[cols_int].map(func)
df_atts[cols_int] = df_atts[cols_int].fillna(0).astype(int)

### Feature Engineering

In [18]:
def regex_neighbor(x):

    match=re.search('(?<=- )[\w ]+', str(x))
    if match:
        return match.group()
    else:
        return x

df_atts.loc[:, 'neighborhood'] = df_atts.address.apply(regex_neighbor)
df_atts.loc[:, 'numberOfSuites'] = df_atts.numberOfSuites.fillna(0).apply(lambda x: re.search('\d+', str(x)).group())
df_atts['total_rental_price'] = df_atts.condo_price + df_atts.rent_price

# to int;
df_atts['numberOfSuites'] = df_atts.numberOfSuites.astype(int)

In [19]:
for index, cols in df_atts.iterrows():
    
    if not isinstance(cols.address, float):
        address = cols.address.split(',')
        
        n = len(address)

        df_atts.loc[index, 'neighborhood']  = regex_neighbor(address[-2])
        df_atts.loc[index, 'city'] = address[-1].split(' - ')[0].strip()

        if n == 3: # means we have street name;

            df_atts.loc[index, 'street'] = address[-3]
            df_atts.loc[index, 'number'] = address[-2].split('-')[0].strip()

In [20]:
df_atts = df_atts.drop(columns = ['address']) # we can drop;

In [21]:
df_atts.dtypes

data-id                    object
ad_type                    object
rstate_type                object
rent_price                float64
condo_price               float64
sell_price                float64
floorSize                   int64
numberOfBathroomsTotal      int64
numberOfParkingSpaces       int64
numberOfRooms               int64
numberOfSuites              int64
FURNISHED                   int64
AIR_CONDITIONING            int64
HOME_OFFICE                 int64
POOL                        int64
GYM                         int64
SAUNA                       int64
LAUNDRY                     int64
link                       object
neighborhood               object
total_rental_price        float64
city                       object
street                     object
number                     object
dtype: object

### Data Cleaning

In [22]:
df_atts.loc[:, 'rstate_type'] = df_atts.rstate_type.str[:-1]  # removing '/' at final of each string;

In [23]:


cols_reord = [
             'data-id', 'rstate_type', 'ad_type',
             'rent_price',  'sell_price',  'condo_price', 'total_rental_price', 'floorSize',
             'neighborhood', 'street', 'number', 'city'] + cols_bool + \
            ['numberOfRooms', 'numberOfSuites', 'numberOfBathroomsTotal', 'numberOfParkingSpaces', 'link']

df_atts = df_atts[cols_reord]

In [24]:
renamed_cols = {'data-id': 'id', 
                'rstate_type': 'kind', 'ad_type': 'rent_or_selling', 
                'rent_price':'price_rent', 'sell_price': 'price_sale', 'condo_price': 'price_condominium', 'total_rental_price': 'rent_plus_condo', 
                'floorSize': 'floor_size', 'number': 'address_number',  
                'AIR_CONDITIONING': 'air_conditioning', 'FURNISHED': 'furnished', 'HOME_OFFICE': 'home_office', 
                "POOL": 'pool', "GYM": 'gym', "LAUNDRY": 'laundry', 'SAUNA': 'sauna',
                'numberOfRooms': 'rooms', 'numberOfSuites': 'suites', 'numberOfBathroomsTotal': 'bathrooms', 'numberOfParkingSpaces': 'parking'}


df_atts = df_atts.rename(columns = renamed_cols)

In [25]:
df_atts.head(2)

,id,kind,rent_or_selling,price_rent,price_sale,price_condominium,rent_plus_condo,floor_size,neighborhood,street,...,home_office,pool,gym,laundry,sauna,rooms,suites,bathrooms,parking,link
0,2746686250,"Terrenos, Lotes e Condomínios para Alugar",Aluguel,50000.0,NaN,NaN,NaN,2500,Jardim Japão,NaN,...,0,0,0,0,0,0,0,0,0,https://www.zapimoveis.com.br/imovel/aluguel-terreno-lote-condominio-jardim-japao-sao-paulo-2500m2-id-2746686250/?source=ranking%2Crp
3,2812097995,Casas à Venda,Venda,8000.0,1722000.0,NaN,NaN,300,Campo Belo,NaN,...,0,0,0,0,0,3,1,3,8,https://www.zapimoveis.com.br/imovel/venda-casa-3-quartos-brooklin-paulista-sao-paulo-300m2-id-2812097995/?source=ranking%2Crp

### Validating Duplicated Listing

In [26]:
# Needed because the same house can be listed by different real estate agencies

columns = list(df_atts.columns)
for i in ['id', 'link']:
    columns.remove(i)

print(f'Number of duplicated listing based on REstate properties: {df_atts.duplicated(subset= columns).sum()}')

Number of duplicated listing based on REstate properties: 0

In [27]:
df_atts = df_atts.drop_duplicates(subset=columns)

df_atts.shape

(107, 24)

### Estatistical Cleaning

<li> outliers

In [28]:
df_atts_sell = df_atts[~df_atts.price_sale.isna()]
df_atts_rent = df_atts[~df_atts.price_rent.isna()]  # as some adtype listed as "For Sale" may contain the price and be able to rent, we can use .isna()

In [29]:
def plot_box_plot(df, sell_or_rent):

    if sell_or_rent == 'rent':
        box_data = df.price_rent / df.floor_size

    elif sell_or_rent == 'sell':
        box_data = df.price_sale / df.floor_size
    
    else:
        raise NameError

    Q1 = np.percentile(box_data, 25)
    Q3 = np.percentile(box_data, 75)
    IQR = Q3 - Q1

    u_bound = Q3 + 1.5*IQR
    l_bound = Q1 - 1.5*IQR

    return {'u_bound': u_bound, 'l_bound': l_bound}

In [30]:
# IQR to remove outliers based on price/floor_size

rent_bounds = plot_box_plot(df_atts_rent, 'rent')
df_atts_rent_adjusted = df_atts_rent[
    ((df_atts_rent.price_rent / df_atts_rent.floor_size) < rent_bounds.get('u_bound')) &
   ( (df_atts_rent.price_rent / df_atts_rent.floor_size) > rent_bounds.get('l_bound') )
]

sale_bounds = plot_box_plot(df_atts_sell, 'sell')
df_atts_sale_adjusted = df_atts_sell[
    ((df_atts_sell.price_rent / df_atts_sell.floor_size) < sale_bounds.get('u_bound')) &
   ( (df_atts_sell.price_rent / df_atts_sell.floor_size) > sale_bounds.get('l_bound') )
]

In [31]:
# making a new index to slice the original dataframe;
new_index = np.concatenate((df_atts_rent_adjusted.index,df_atts_sale_adjusted.index))
new_index = list(set(new_index))

df_atts = df_atts.loc[new_index, :]

### Postgres Ingestion;

In [32]:
# db credentials come from the file app.properties

uri = p.get('uri').data
engine = create_engine(uri)

with engine.connect() as con:
    con.execute(text("CREATE SCHEMA if not exists zap"))
    con.commit()

In [33]:
# drop views to update silver table; 
with engine.connect() as conn:
    views_list = conn.execute(
    text("""select table_name 
            from information_schema.views
            where table_schema = 'zap' """)).fetchall() # getting the view's name that exists;


    for view in views_list:  # dropping them because it's needed;
        conn.execute(text(f"DROP VIEW zap.{view[0]}"))
        conn.commit() 


df_atts.to_sql('silver_zapimoveis', schema='zap', # now its gonna work;
    con = uri, if_exists='replace', index = False, 
    dtype={'price_rent': Numeric, 'price_sale': Numeric, 'price_condominium': Numeric, 'rent_plus_condo': Numeric})

101

In [34]:
### call run dbt;
subprocess.run("dbt run", shell=True)

04:12:49  Running with dbt=1.9.2
04:12:49  Registered adapter: postgres=1.9.0
04:12:51  Found 1 model, 6 data tests, 1 source, 433 macros
04:12:51
04:12:51  Concurrency: 2 threads (target='dev')
04:12:51
04:12:51  1 of 1 START sql table model zap.gold_floorsize_ranked_avg_prices .............. [RUN]
04:12:52  1 of 1 OK created sql table model zap.gold_floorsize_ranked_avg_prices ......... [SELECT 101 in 0.40s]
04:12:52
04:12:52  Finished running 1 table model in 0 hours 0 minutes and 0.97 seconds (0.97s).
04:12:52
04:12:52  Completed successfully
04:12:52
04:12:52  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1

CompletedProcess(args='dbt run', returncode=0)

### END

In [35]:
with engine.connect() as conn:
    query = text("SELECT * FROM zap.gold_floorsize_ranked_avg_prices")
    data = conn.execute(query).fetchall()

    df_gold = pd.DataFrame(data)

In [36]:
df_gold.he

AttributeError: 'DataFrame' object has no attribute 'he'

In [ ]:
# export and save for using in Tableau (Data Viz)
df_gold.to_csv('zap-gold_data-to_tableau.csv', index = False)